
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
push:
  branches: [ master ]

jobs:
build:
  name: Build and Run Tests
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v1
  

    - name: Build and Run Tests
      run: mvn test --batch-mode --fail-at-end
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: find chrome location
      run: |
        ls -a
        
    - name: try to navigate chrome
      run: |
cd  /opt/google/chrome/google-chrome


 
